"""TIZIRI Pinterest auto-publisher.

Meant to run daily via Windows Task Scheduler, same pattern as
scripts/instagram/publish_due.py. Reads calendar.json (generated by
generate_calendar.py from data/rugs.json), creates at most ONE due pin
per run via the Pinterest API v5, records progress in a local state
file, and refreshes the access token when it gets old.

No external dependencies (stdlib only). No secrets in this file:
  app id/secret  C:\\Users\\nigel\\.pin-app-id.txt / .pin-app-secret.txt
  access token   C:\\Users\\nigel\\.pin-token.txt
  refresh token  C:\\Users\\nigel\\.pin-refresh-token.txt
  token birthday C:\\Users\\nigel\\.pin-token-date.txt
  state          C:\\Users\\nigel\\.pin-post-state.json
  log            C:\\Users\\nigel\\.pin-post-log.txt
"""
import base64
import html
import json
import urllib.error
import urllib.parse
import urllib.request
from datetime import date, datetime, timedelta
from pathlib import Path

HOME = Path.home()
HERE = Path(__file__).parent
ROOT = HERE.resolve().parents[1]

APP_ID_FILE = HOME / ".pin-app-id.txt"
APP_SECRET_FILE = HOME / ".pin-app-secret.txt"
TOKEN_FILE = HOME / ".pin-token.txt"
REFRESH_FILE = HOME / ".pin-refresh-token.txt"
TOKEN_DATE_FILE = HOME / ".pin-token-date.txt"
STATE_FILE = HOME / ".pin-post-state.json"
LOG_FILE = HOME / ".pin-post-log.txt"

CALENDAR_FILE = HERE / "calendar.json"
RUGS_FILE = ROOT / "data" / "rugs.json"

API = "https://api.pinterest.com/v5"
POST_HOUR = 9  # never publish before 9 AM local

# style -> board id. Styles without a dedicated board fall back to the
# general "Moroccan Rugs" board. IDs from a live `GET /v5/boards` call
# against the production account on 2026-07-13.
BOARD_BY_STYLE = {
    "Beni Ourain": "808325901809608705",
    "Boujaad": "808325901809611596",
    "Azilal": "808325901809608706",
}
FALLBACK_BOARD = "808325901809608626"  # Moroccan Rugs


def log(msg):
    line = f"[{datetime.now():%Y-%m-%d %H:%M:%S}] {msg}"
    print(line)
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(line + "\n")


def api(path, token, params=None, method="GET"):
    url = f"{API}/{path}"
    data = None
    headers = {"Authorization": f"Bearer {token}"}
    if params is not None and method == "POST":
        data = json.dumps(params).encode("utf-8")
        headers["Content-Type"] = "application/json"
    elif params:
        url += "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            return json.loads(r.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        raise RuntimeError(f"{method} {path} -> {e.code}: {e.read().decode()}")


def refresh_token_if_old(token):
    try:
        born = date.fromisoformat(TOKEN_DATE_FILE.read_text().strip())
    except Exception:
        TOKEN_DATE_FILE.write_text(date.today().isoformat())
        return token
    if (date.today() - born).days < 25:
        return token
    try:
        app_id = APP_ID_FILE.read_text().strip()
        app_secret = APP_SECRET_FILE.read_text().strip()
        refresh_token = REFRESH_FILE.read_text().strip()
        auth = base64.b64encode(f"{app_id}:{app_secret}".encode()).decode()
        body = urllib.parse.urlencode({
            "grant_type": "refresh_token",
            "refresh_token": refresh_token,
        }).encode()
        req = urllib.request.Request(
            "https://api.pinterest.com/v5/oauth/token",
            data=body,
            headers={
                "Authorization": f"Basic {auth}",
                "Content-Type": "application/x-www-form-urlencoded",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=30) as r:
            token_data = json.loads(r.read().decode())
        TOKEN_FILE.write_text(token_data["access_token"])
        if token_data.get("refresh_token"):
            REFRESH_FILE.write_text(token_data["refresh_token"])
        TOKEN_DATE_FILE.write_text(date.today().isoformat())
        log("Token refreshed")
        return token_data["access_token"]
    except Exception as e:
        log(f"WARNING: token refresh failed: {e}")
        return token


def board_for(style):
    return BOARD_BY_STYLE.get(style, FALLBACK_BOARD)


def build_pin(rug):
    dims = html.unescape(rug["dimensions"])
    title = f"{rug['name']} - {rug['category']}"[:100]
    description = f"{rug['description']} {dims}."[:500]
    return {
        "board_id": board_for(rug["style"]),
        "title": title,
        "description": description,
        "link": f"https://tizirirugs.com/rugs/{rug['slug']}",
        "media_source": {
            "source_type": "image_url",
            "url": rug["images"][0],
        },
    }


def main():
    token = TOKEN_FILE.read_text().strip()
    token = refresh_token_if_old(token)

    cal = json.loads(CALENDAR_FILE.read_text(encoding="utf-8"))
    rugs_by_slug = {r["slug"]: r for r in json.loads(RUGS_FILE.read_text(encoding="utf-8"))}

    state = {}
    if STATE_FILE.exists():
        state = json.loads(STATE_FILE.read_text(encoding="utf-8"))

    now = datetime.now()
    due = [p for p in cal["posts"]
           if p["id"] not in state
           and datetime.fromisoformat(p["date"]) + timedelta(hours=POST_HOUR) <= now]
    if not due:
        log("Nothing due.")
        return
    if len(due) > 1:
        log(f"{len(due)} pins overdue; publishing oldest only (one per run).")

    post = sorted(due, key=lambda p: p["date"])[0]
    rug = rugs_by_slug.get(post["slug"])
    if not rug:
        log(f"ERROR: {post['id']} references unknown rug slug '{post['slug']}'; skipping.")
        state[post["id"]] = {"skipped": datetime.now().isoformat(), "reason": "unknown slug"}
        STATE_FILE.write_text(json.dumps(state, indent=1), encoding="utf-8")
        return
    if rug.get("availability") != "InStock":
        log(f"SKIP {post['id']}: {rug['slug']} is not InStock ({rug.get('availability')}).")
        state[post["id"]] = {"skipped": datetime.now().isoformat(), "reason": "not in stock"}
        STATE_FILE.write_text(json.dumps(state, indent=1), encoding="utf-8")
        return

    pin = build_pin(rug)
    log(f"Publishing {post['id']} ({rug['slug']}) to board {pin['board_id']}...")
    r = api("pins", token, pin, method="POST")
    state[post["id"]] = {"published": datetime.now().isoformat(), "pin_id": r["id"]}
    STATE_FILE.write_text(json.dumps(state, indent=1), encoding="utf-8")
    log(f"PUBLISHED {post['id']} -> pin id {r['id']}")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        log(f"ERROR: {e}")
        raise
